"""add_reprocess_tasks_table

Revision ID: f75fefbd4a00
Revises: 9f218b93016c
Create Date: 2026-05-28 17:42:19.674556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75fefbd4a00'
down_revision: Union[str, Sequence[str], None] = '9f218b93016c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reprocess_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_category', sa.String(length=20), nullable=True),
    sa.Column('result_confidence', sa.Float(), nullable=True),
    sa.Column('result_resolution', sa.String(length=30), nullable=True),
    sa.Column('result_votes', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reprocess_tasks_email_id'), 'reprocess_tasks', ['email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reprocess_tasks_email_id'), table_name='reprocess_tasks')
    op.drop_table('reprocess_tasks')
    # ### end Alembic commands ###
